In [1]:
import yfinance as yf
import pandas as pd

skew_data = yf.download("^SKEW", start="2000-01-01", end="2026-03-09")

print(f"抓到了 {len(skew_data)} 天的数据")
print(skew_data.head())

skew_data.to_csv("CBOE_SKEW_Full_2000_2026.csv")

/tmp/ipykernel_1639/3759226119.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  skew_data = yf.download("^SKEW", start="2000-01-01", end="2026-03-09")
[*********************100%***********************]  1 of 1 completed

抓到了 6510 天的数据
Price            Close        High         Low        Open Volume
Ticker           ^SKEW       ^SKEW       ^SKEW       ^SKEW  ^SKEW
Date
2000-01-03  117.839996  117.839996  117.839996  117.839996      0
2000-01-04  114.220001  114.220001  114.220001  114.220001      0
2000-01-05  114.820000  114.820000  114.820000  114.820000      0
2000-01-06  114.870003  114.870003  114.870003  114.870003      0
2000-01-07  117.349998  117.349998  117.349998  117.349998      0

In [2]:
skew_data = yf.download("^VIX", start="2000-01-01", end="2026-03-09")

print(f"抓到了 {len(skew_data)} 天的数据")
print(skew_data.head())

skew_data.to_csv("VIX.csv")

/tmp/ipykernel_1639/3869104180.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  skew_data = yf.download("^VIX", start="2000-01-01", end="2026-03-09")
[*********************100%***********************]  1 of 1 completed

抓到了 6583 天的数据
Price           Close       High        Low       Open Volume
Ticker           ^VIX       ^VIX       ^VIX       ^VIX   ^VIX
Date
2000-01-03  24.209999  26.150000  23.980000  24.360001      0
2000-01-04  27.010000  27.180000  24.799999  24.940001      0
2000-01-05  26.410000  29.000000  25.850000  27.980000      0
2000-01-06  25.730000  26.709999  24.700001  26.680000      0
2000-01-07  21.719999  25.170000  21.719999  25.139999      0

In [3]:
from google.colab import drive
import os

drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df_skew = pd.read_csv("/content/drive/MyDrive/557project/CBOE_SKEW_Full_2000_2026.csv")
df_vix = pd.read_csv("/content/drive/MyDrive/557project/VIX.csv")
df_spread = pd.read_csv("/content/drive/MyDrive/557project/spread_10y2y.csv")
df_oas = pd.read_csv("/content/drive/MyDrive/557project/hy_oas.csv")

In [6]:
# 定义一个列表方便批量操作
dataframes = {
    "SKEW": df_skew,
    "VIX": df_vix,
    "10y-2y Spread": df_spread,
    "HY OAS": df_oas
}

for name, df in dataframes.items():
    print(f"--- {name} ---")
    print(f"行列维度 (Rows, Cols): {df.shape}")
    print("前 3 行预览:")
    display(df.head(3)) # 在 Colab/Jupyter 里用 display 更好看
    print("\n")

--- SKEW ---
行列维度 (Rows, Cols): (6512, 6)
前 3 行预览:

,Price,Close,High,Low,Open,Volume
0,Ticker,^SKEW,^SKEW,^SKEW,^SKEW,^SKEW
1,Date,NaN,NaN,NaN,NaN,NaN
2,2000-01-03,117.83999633789062,117.83999633789062,117.83999633789062,117.83999633789062,0

--- VIX ---
行列维度 (Rows, Cols): (6585, 6)
前 3 行预览:

,Price,Close,High,Low,Open,Volume
0,Ticker,^VIX,^VIX,^VIX,^VIX,^VIX
1,Date,NaN,NaN,NaN,NaN,NaN
2,2000-01-03,24.209999084472656,26.149999618530273,23.979999542236328,24.360000610351562,0

--- 10y-2y Spread ---
行列维度 (Rows, Cols): (6830, 2)
前 3 行预览:

  observation_date  T10Y2Y
0       2000-01-03    0.20
1       2000-01-04    0.19
2       2000-01-05    0.24

--- HY OAS ---
行列维度 (Rows, Cols): (6919, 2)
前 3 行预览:

  observation_date  BAMLH0A0HYM2
0       2000-01-03          4.68
1       2000-01-04          4.81
2       2000-01-05          4.77

In [11]:
df_vix = df_vix.iloc[2:].copy()

df_vix.set_index('Price', inplace=True)
df_vix.index.name = 'Date'

print(df_vix.head())

                         Close                High                 Low  \
Date
2000-01-03  24.209999084472656  26.149999618530273  23.979999542236328
2000-01-04  27.010000228881836   27.18000030517578  24.799999237060547
2000-01-05   26.40999984741211                29.0  25.850000381469727
2000-01-06  25.729999542236328  26.709999084472656  24.700000762939453
2000-01-07  21.719999313354492  25.170000076293945  21.719999313354492

                          Open Volume
Date
2000-01-03  24.360000610351562      0
2000-01-04  24.940000534057617      0
2000-01-05  27.979999542236328      0
2000-01-06   26.68000030517578      0
2000-01-07  25.139999389648438      0

In [13]:
print(df_skew.head())

                         Close                High                 Low  \
Date
2000-01-05  114.81999969482422  114.81999969482422  114.81999969482422
2000-01-06  114.87000274658203  114.87000274658203  114.87000274658203
2000-01-07   117.3499984741211   117.3499984741211   117.3499984741211
2000-01-10   115.7300033569336   115.7300033569336   115.7300033569336
2000-01-11   114.9800033569336   114.9800033569336   114.9800033569336

                          Open Volume
Date
2000-01-05  114.81999969482422      0
2000-01-06  114.87000274658203      0
2000-01-07   117.3499984741211      0
2000-01-10   115.7300033569336      0
2000-01-11   114.9800033569336      0

In [15]:
for df in [df_spread, df_oas]:
    df.columns = df.columns.str.strip()

In [16]:
for df in [df_spread, df_oas]:
    df['observation_date'] = pd.to_datetime(df['observation_date'])
    df.set_index('observation_date', inplace=True)

In [17]:
print(df_spread.head())
print(df_oas.head())

                  T10Y2Y
observation_date
2000-01-03          0.20
2000-01-04          0.19
2000-01-05          0.24
2000-01-06          0.22
2000-01-07          0.21
                  BAMLH0A0HYM2
observation_date
2000-01-03                4.68
2000-01-04                4.81
2000-01-05                4.77
2000-01-06                4.82
2000-01-07                4.86

In [21]:
for df in [df_skew, df_vix]:
    df.index = pd.to_datetime(df.index)

In [22]:
data_final = pd.concat([
    df_skew['Close'].rename('SKEW'),
    df_vix['Close'].rename('VIX'),
    df_spread['T10Y2Y'].rename('Spread'),
    df_oas['BAMLH0A0HYM2'].rename('OAS')
], axis=1)

In [25]:
print(data_final.head())
print(data_final.shape)

                          SKEW                 VIX  Spread   OAS
2000-01-03                 NaN  24.209999084472656    0.20  4.68
2000-01-04                 NaN  27.010000228881836    0.19  4.81
2000-01-05  114.81999969482422   26.40999984741211    0.24  4.77
2000-01-06  114.87000274658203  25.729999542236328    0.22  4.82
2000-01-07   117.3499984741211  21.719999313354492    0.21  4.86
(6919, 4)

In [26]:
print("原始 shape:", data_final.shape)
print("dropna 后 shape:", data_final.dropna().shape)
print("\n每列缺失数：")
print(data_final.isna().sum())

原始 shape: (6919, 4)
dropna 后 shape: (6459, 4)

每列缺失数：
SKEW      411
VIX       336
Spread    373
OAS        83
dtype: int64

In [27]:
data_model = data_final.dropna().copy()
print(data_model.shape)

(6459, 4)

In [29]:
data_model.to_csv("4columns_na_dropped.csv")